// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a DIRECT (non-pooled) connection — Neon's pooler
    // can't run schema changes. Falls back to DATABASE_URL if DIRECT_URL
    // isn't set (e.g. when using a single local connection string).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
